# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1LQeHILCvciDjWb12FEIbPLgGP1CjBx

### Mount Google Drive

To load data from Google Drive, you first need to mount your Drive. This will allow your Colab notebook to access files stored in your Google Drive.
"""

from google.colab import drive
drive.mount('/content/drive')

# 1. Das offizielle Starter Kit herunterladen
!git clone https://github.com/Towers-D/NAS-Comp-Starter-Kit.git NAS-Comp

# 2. Den "datasets" Ordner löschen (falls einer existiert)
!rm -rf /content/NAS-Comp/datasets

# 3. Deine Datensätze aus dem Drive als "datasets" Ordner in das Projekt verlinken.
# ACHTUNG: Wenn dein Ordner im Drive anders heißt als "NAS-Datasets", ändere den Namen hier!
!ln -s /content/drive/MyDrive/NAS-Datasets /content/NAS-Comp/datasets

# 4. Kurz testen, ob Colab die Dateien findet:
!ls -la /content/NAS-Comp/datasets/

from google.colab import files
import os

print("Bitte wähle die submission.zip von deinem PC aus:")
uploaded = files.upload()

# Den Ordner vorbereiten und entpacken
!rm -rf /content/NAS-Comp/submission
!mkdir -p /content/NAS-Comp/submission
!unzip -o submission.zip -d /content/NAS-Comp/submission/

!pip install -q scikit-learn
import torch
print(f"GPU aktiv: {torch.cuda.is_available()}")
print(f"Grafikkarte: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'Keine'}")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/NAS-Comp

# Dies startet den kompletten Durchlauf: Build -> Run -> Score
!make submission=submission all